title: DeepSpeed
email: deepspeed@microsoft.com
description: >-
  DeepSpeed is a deep learning optimization library that makes distributed
  training easy, efficient, and effective.

locale : "en-US"

repository: microsoft/DeepSpeed
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.deepspeed.ai" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.0"
minimal_mistakes_skin : "air"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate

#paginate: 10
#paginate_path: /blog/page:num

include: ["_pages"]
exclude: ["code-docs"]

collections:
  tutorials:
    output: true
    permalink: /:collection/:path/
    order:
      - advanced-install.md
      - getting-started.md
      - azure.md
      - cifar-10.md
      - bert-pretraining.md
      - bert-finetuning.md
      - transformer_kernel.md
      - megatron.md
      - one-cycle.md
      - lrrt.md
      - zero.md
      - flops-profiler.md

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
      sneak_preview: false
      toc: true
      toc_label: "Contents"
      sidebar:
        nav: "lnav"
  - scope:
      path: "_pages"
    values:
      permalink: /docs/:basename/
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      share: true

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-169781858-1"

timezone: America/Los_Angeles
breadcrumbs: true

press_release_v3: https://www.microsoft.com/en-us/research/blog/deepspeed-extreme-scale-model-training-for-everyone/
